# Generated by Django 3.2.5 on 2022-07-06 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_alter_user_age'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='describe',
        ),
        migrations.RemoveField(
            model_name='user',
            name='hobby',
        ),
    ]
